# 倒计时目标日期、时间
Calendar:
  Year: 2026
  Month: 1
  Day: 1
  Hour: 0
  Minute: 0
  Second: 0

# 是否自动启动线程
AutoStart: true

# 倒计时底部消息 A为大于1小时时显示的内容,B为小于1小时时显示的内容
Bottom:
  A: "    §l§f迎接2026 @hour:@minute:@second\n§r§7在MC一起倒数,领取新年大礼包!"
  B: "      §l§f迎接2026 @minute:@second\n§r§7在MC一起倒数,领取新年大礼包!"

# 倒计时标题显示类型
# 填写true为使用Simple模式，填写false为使用Custom模式
SimpleMode: true

# Custom倒计时标题
Custom_Title:
  30s: "§l§b⌛ §f30 §b⌛"
  29s: "§l§b⌛ §f29 §b⌛"
  28s: "§l§b⌛ §f28 §b⌛"
  27s: "§l§b⌛ §f27 §b⌛"
  26s: "§l§b⌛ §f26 §b⌛"
  25s: "§l§b⌛ §f25 §b⌛"
  24s: "§l§b⌛ §f24 §b⌛"
  23s: "§l§b⌛ §f23 §b⌛"
  22s: "§l§b⌛ §f22 §b⌛"
  21s: "§l§b⌛ §f21 §b⌛"
  20s: "§l§b⌛ §f20 §b⌛"
  19s: "§l§b⌛ §f19 §b⌛"
  18s: "§l§b⌛ §f18 §b⌛"
  17s: "§l§b⌛ §f17 §b⌛"
  16s: "§l§b⌛ §f16 §b⌛"
  15s: "§l§b⌛ §f15 §b⌛"
  14s: "§l§b⌛ §f14 §b⌛"
  13s: "§l§b⌛ §f13 §b⌛"
  12s: "§l§b⌛ §f12 §b⌛"
  11s: "§l§b⌛ §f11 §b⌛"
  10s: "§l§b⌛ §f10 §b⌛"
  9s: "§l§b⌛ §f9 §b⌛"
  8s: "§l§b⌛ §f8 §b⌛"
  7s: "§l§b⌛ §f7 §b⌛"
  6s: "§l§b⌛ §f6 §b⌛"
  5s: "§l§b⌛ §f5 §b⌛"
  4s: "§l§b⌛ §f4 §b⌛"
  3s: "§l§b⌛ §f3 §b⌛"
  2s: "§l§b⌛ §f2 §b⌛"
  1s: "§l§b⌛ §f1 §b⌛"
  0s: "§l§b⌛ §f0 §b⌛"

# Custom倒计时副标题
Custom_SubTitle:
  30s: "迎接2026, 一起倒计时"
  29s: "迎接2026, 一起倒计时"
  28s: "迎接2026, 一起倒计时"
  27s: "迎接2026, 一起倒计时"
  26s: "迎接2026, 一起倒计时"
  25s: "迎接2026, 一起倒计时"
  24s: "迎接2026, 一起倒计时"
  23s: "迎接2026, 一起倒计时"
  22s: "迎接2026, 一起倒计时"
  21s: "迎接2026, 一起倒计时"
  20s: "迎接2026, 一起倒计时"
  19s: "迎接2026, 一起倒计时"
  18s: "迎接2026, 一起倒计时"
  17s: "迎接2026, 一起倒计时"
  16s: "迎接2026, 一起倒计时"
  15s: "迎接2026, 一起倒计时"
  14s: "迎接2026, 一起倒计时"
  13s: "迎接2026, 一起倒计时"
  12s: "迎接2026, 一起倒计时"
  11s: "迎接2026, 一起倒计时"
  10s: "迎接2026, 一起倒计时"
  9s: "迎接2026, 一起倒计时"
  8s: "迎接2026, 一起倒计时"
  7s: "迎接2026, 一起倒计时"
  6s: "迎接2026, 一起倒计时"
  5s: "迎接2026, 一起倒计时"
  4s: "迎接2026, 一起倒计时"
  3s: "迎接2026, 一起倒计时"
  2s: "迎接2026, 一起倒计时"
  1s: "迎接2026, 一起倒计时"
  0s: "迎接2026, 一起倒计时"

# Simple倒计时标题
# A为21-30秒显示的内容
# B为11-20秒显示的内容
# C为0-10秒显示的内容
Simple_Title:
  A: "§l§b⌛ §f@second §b⌛"
  B: "§l§b⌛ §f@second §b⌛"
  C: "§l§c❤ §f@second §c❤"
  Title: "§l§f2026 §c元旦快乐"

# Simple倒计时副标题
# A为21-30秒显示的内容
# B为11-20秒显示的内容
# C为0-10秒显示的内容
Simple_SubTitle:
  A: "迎接2026, 一起倒计时"
  B: "迎接2026, 一起倒计时"
  C: "迎接2026, 一起倒计时"
  SubTitle: ""

# 最终显示的标题
Final_Title:
  Title: "§l§f2026 §c新年快乐"
  SubTitle: ""

# 活动奖励,执行奖励命令
# 命令后添加&con为控制台执行
Rewards:
  - "say 新年快乐 @player&con"

# 奖励消息
RewardMessage: "跨年大礼包将分批发出,请稍后在邮件中领取"

# 发送标题、放烟花、发送奖励执行延迟
DelayTime: 20

# 底部奖励消息内容
TipMessage: "新春奖励将分批发出,请稍后在邮件中领取"

# 底部奖励消息循环间隔时长
TipMessagePeriod: 20

# 底部奖励消息延迟时长
TipMessageDelayTime: 40

# 底部奖励消息显示时长
TipShowTime: 1200

# 使用外置音乐播放器播放音乐
# 推荐使用MusicPlus
# https://github.com/Nissining/MusicPlus
PlayMusicCmd: "mplus play 0"

# 播放音乐延迟时长
PlayMusicDelayTime: 10

#烟花秀
FireworkShow: true

#烟花秀坐标
FireworkPosition:
  - "0:100:0:world"
  - "5:100:0:world"